name: PR_Review

on:
  pull_request:
    branches: [staging]
    types: [opened,edited ,reopened]

jobs:
  PR_Review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.2
      - name: Install app dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      - name: Run lint
        uses: kitek/dartanalyzer-annotations-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          check_name: "Automatically Linting the Dart Code"
          commit_sha: ${{ github.event.pull_request.head.sha }}

      - name: Slack CI Failure Notification
        if: failure() || cancelled()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#f32013"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Pull Request Fail"
          SLACK_TITLE: Pull Request Faild in automated check ${{ github.sha }}
          SLACK_USERNAME: Librarian_app
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack CI Success Notification
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#2eb887"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Pull request Success :rocket: "
          SLACK_TITLE: Pull Request Passed for Manual Approuval ${{ github.sha }}
          SLACK_USERNAME: Librarian_app
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
