name: Staging

on:
  pull_request:
    types: [closed]
    branches: [staging]

jobs:
  Staging:
    runs-on: ubuntu-latest

    steps:
      - id: compute_tag
        uses: craig-day/compute-tag@v10
        with:
          github_token: ${{ github.token }}
          version_type: patch

      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.2

      - name: Install app dependencies
        run: flutter pub get

      - name: Test app
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      - name: Run lint
        uses: kitek/dartanalyzer-annotations-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          check_name: "Staging"
          commit_sha: ${{ github.event.pull_request.head.sha }}

      - name: Slack CI Failure Notification
        if: failure() || cancelled()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#f32013"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Pull request failed to pass staging requirements"
          SLACK_TITLE: Pull Request Auto-Review Faild ${{ github.sha }}
          SLACK_USERNAME: Librarian_app
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack CI Success Notification
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#2eb887"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Pull request successfully moved to staging  :rocket: "
          SLACK_TITLE: Pull Request Reviewed and Accepted ${{ github.sha }}
          SLACK_USERNAME: Librarian_app
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
